CREATE TABLE storia(
	Id SERIAL PRIMARY KEY,
	number_group INTEGER NOT NULL,
	categoria VARCHAR(50) NOT NULL,
	titolo VARCHAR(50) NOT NULL,
	intro VARCHAR(50) NOT NULL,
	testo VARCHAR NOT NULL,
	link_ VARCHAR NOT NULL,
	image VARCHAR NOT NULL
)